# Monitor API Key Secret
# Contains the API key for authenticating with Team Flags

apiVersion: v1
kind: Secret
metadata:
  name: monitor-secret
  # TODO: Change namespace to your team name
  namespace: the-hole
  labels:
    app: team-monitor
type: Opaque
stringData:
  # API key will be pre-filled when you download from Mission Control
  API_KEY: "tfk_ITYWv7Bg5xvZPcSlNwuVrbrwBur66ol-pjZrbOYNRRo"
